docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "tests/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"
          - ".github/dependabot.yml"

source:
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
